{application,erlypusher,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,cowboy]},
              {mod,{erlypusher_app,[]}},
              {env,[]},
              {modules,[api_handler,erlypusher,erlypusher_app,erlypusher_sup,
                        main_page,mochijson2,uuid,websocket_handler]}]}.
